version: '3.1'

services:
  swoole:
    container_name: swoole
    build:
      context: .
      dockerfile: ./docker/swoole/Dockerfile
    ports:
      - '9502:9502'
    volumes:
      - ./:/app
    working_dir: /app
#    entrypoint: 'php /app/index.php'

  apache:
    container_name: apache
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
